# Generated by Django 5.2.1 on 2025-06-01 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='mutual_friends',
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='mutual_friends',
            field=models.ManyToManyField(blank=True, related_name='mutual_friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
