# Generated by Django 5.2.1 on 2025-06-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_friendlist_mutual_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='total_prinicipal_amount',
            new_name='total_principal_amount',
        ),
    ]
