# Generated by Django 5.2.1 on 2025-06-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_total_prinicipal_amount_transactions_total_principal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitwise',
            name='syndicator_id',
            field=models.ForeignKey(default='24670e66-5fc4-401a-89ec-bf643330021b', on_delete=django.db.models.deletion.CASCADE, related_name='splitwise_entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
