# Generated by Django 5.2.1 on 2025-06-28 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_splitwise_syndicator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='risk_taker_commission',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transactions',
            name='risk_taker_flag',
            field=models.BooleanField(default=False),
        ),
    ]
