# Generated by Django 5.2.1 on 2025-07-16 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transactions_risk_taker_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='lender_name',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
