# Generated by Django 5.2.1 on 2025-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transactions_end_date_transactions_lender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='month_period_of_loan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
